version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "basic-lambda-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qgz5n1fpubn8"
s3_prefix = "basic-lambda-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "REGION=\"us-east-1\""
